"""Stable packet records and schemas for Sippycup's capture oracle."""

from .adapter import (
    CaptureDecodeError,
    parse_tshark_json,
    probe_capture_format,
    tshark_json_args,
)
from .dialogs import (
    DialogRecord,
    DialogState,
    Reconstruction,
    TransactionRecord,
    TransactionState,
    reconstruct_dialogs,
    reconstruct_transactions,
)
from .media import (
    Applicability,
    AssertionResult,
    CorrelationKind,
    MediaAnalysis,
    MediaDirection,
    MediaExpectations,
    RtpStream,
    evaluate_invariants,
    correlate_streams,
    partition_media_frames,
)
from .records import (
    ASSERTION_SCHEMA_VERSION,
    PACKET_RECORD_SCHEMA_VERSION,
    RESULT_SCHEMA_VERSION,
    CaptureFormat,
    CaptureRecord,
    CaptureStatus,
    EvidenceRef,
    FrameRecord,
    Known,
    Unknown,
    UnknownReason,
    Verdict,
    dumps_record,
    to_primitive,
)

__all__ = [
    "ASSERTION_SCHEMA_VERSION",
    "Applicability",
    "AssertionResult",
    "PACKET_RECORD_SCHEMA_VERSION",
    "RESULT_SCHEMA_VERSION",
    "CaptureDecodeError",
    "CaptureFormat",
    "CaptureRecord",
    "CaptureStatus",
    "CorrelationKind",
    "DialogRecord",
    "DialogState",
    "EvidenceRef",
    "FrameRecord",
    "Known",
    "MediaAnalysis",
    "MediaDirection",
    "MediaExpectations",
    "Reconstruction",
    "RtpStream",
    "Unknown",
    "UnknownReason",
    "TransactionRecord",
    "TransactionState",
    "Verdict",
    "dumps_record",
    "evaluate_invariants",
    "correlate_streams",
    "partition_media_frames",
    "parse_tshark_json",
    "probe_capture_format",
    "reconstruct_dialogs",
    "reconstruct_transactions",
    "to_primitive",
    "tshark_json_args",
]
